sudo: false
language: rust

cache:
  cargo: true
  directories:
    - $HOME/gcc-arm-none-eabi-6_2-2016q4

os:
  - linux

# If you change this, you must also change Getting_Started.md, Makefile.common,
# and Vagrantfile.
rust:
  - nightly-2018-06-14

before_install:
  - ./.travis-install-gcc
  - export PATH="$PATH:$HOME/gcc-arm-none-eabi-6_2-2016q4/bin"

before_script:
  - npm install -g markdown-toc

script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - tools/run_cargo_fmt.sh diff
  - make allboards
  - tools/toc.sh

